### ISSUE TITLE
Attempting to paste using Ctrl + V results in a TypeError.

### ISSUE THREAD

**Issue by ghost** [romgrk/termrk#11]
Hello

I receive the following TypeError when I attempt to paste text into the terminal:

```
TypeError: undefined is not a function
  at space-pen-div.registerCommands.core:paste (/home/me/.atom/packages/Termrk/lib/termrk-view.coffee:92:31)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:238:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at TermrkView.module.exports.TermrkView.keydownListener (/home/me/.atom/packages/Termrk/lib/termrk-view.coffee:134:22)
  at TermrkView.keydownListener (/home/me/.atom/packages/Termrk/lib/termrk-view.coffee:2:1)
```

I hope this backtrace provides enough information to be able to debug the issue. Let me know if there is something else I can do.

Thanks in advance

**Comment by romgrk** [comment]
Fixed
