### ISSUE TITLE
the case of python 3.4

### ISSUE THREAD

**Issue by fbob** [romgrk/termrk#3]
Atom v 0.199.0 on Kubuntu 15.04 

Python version > 3 seems to be not compatible with Termrk@0.1.1
I have also python 2.7 installed on my system but don't know how to pass the --python switch to point to Python >= v2.5.0 & < 3.0.0. 

```
Installing “Termrk@0.1.1” failed.Hide output…

> pty.js@0.2.7-1 install /tmp/apm-install-dir-115418-18286-1w29zv4/node_modules/Termrk/node_modules/pty.js
> node-gyp rebuild


gyp ERR! configure error 
gyp ERR! stack Error: Python executable "python" is v3.4.3, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:108:14)
gyp ERR! stack     at /usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:97:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:656:7)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at maybeClose (child_process.js:766:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
gyp ERR! System Linux 3.19.0-16-generic
gyp ERR! command "node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-115418-18286-1w29zv4/node_modules/Termrk/node_modules/pty.js
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 3.19.0-16-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/beaubert/.atom/.apm/.apmrc" "--userconfig" "/home/beaubert/.atom/.apmrc" "install" "/tmp/d-115418-18286-1jveqfe/package.tgz" "--target=0.22.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.2.7-1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.2.7-1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-115418-18286-1w29zv4/npm-debug.log
```

**Comment by fbob** [comment]
I've just temporary changed my path to point to python 2.7 before installing the plugin and I was able to install it. 

I'm now facing  issue #1 where pane is zero pixels tall

**Comment by romgrk** [comment]
As I see it, I can't solve the problem from my side because the python is used by pty.js module, and I don't want to edit that from here. I'll mark as closed, but I'll check if I can do something like a PR to pty.js.

Issue #1 should be fixed now.
