### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by jvbridge** [romgrk/termrk#34]
1. make a virtual machine with vagrant and ssh into it (running CentOS  6.6)
2. paste command
3. scroll up

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.3
**Thrown From**: [Termrk](https://github.com/romgrk/termrk) package, v0.1.17
### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At /Users/jonathanbridge/.atom/packages/Termrk/node_modules/term.js/src/term.js:1208

TypeError: Cannot read property '0' of undefined
    at Terminal.refresh (/Users/jonathanbridge/.atom/packages/Termrk/node_modules/term.js/src/term.js:1208:18)
    at Terminal.refresh (/Users/jonathanbridge/.atom/packages/Termrk/lib/termjs-fix.coffee:127:41)
    at Terminal._cursorBlink (/Users/jonathanbridge/.atom/packages/Termrk/node_modules/term.js/src/term.js:1324:8)
    at _blinker (/Users/jonathanbridge/.atom/packages/Termrk/node_modules/term.js/src/term.js:1341:10)
```
### Commands

```
     -0:58.2.0 core:paste (input.input-keylistener)
```
### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "disabledPackages": [
      "term2",
      "terminal-panel"
    ]
  },
  "Termrk": {}
}
```
### Installed Packages

``` coffee
# User
Termrk, v0.1.17
docblockr, v0.7.2
seti-syntax, v0.4.0
seti-ui, v0.7.1

# Dev
No dev packages
```

**Comment by ghost** [comment]
@jvbridge See if my current PR fixes your problem - https://github.com/romgrk/termrk/pull/32

**Comment by romgrk** [comment]
Closing in favor of https://github.com/romgrk/termrk/issues/27.
