### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by amazingsam** [romgrk/termrk#37]
[Enter steps to reproduce below:]
1. Event mouse scroll down when in terminal

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [Termrk](https://github.com/romgrk/termrk) package, v0.1.17
### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At /Users/sam/.atom/packages/Termrk/node_modules/term.js/src/term.js:1208

TypeError: Cannot read property '0' of undefined
  at Terminal.refresh (/Users/sam/.atom/packages/Termrk/node_modules/term.js/src/term.js:1208:18)
  at Terminal.refresh (/Users/sam/.atom/packages/Termrk/lib/termjs-fix.coffee:127:9)
  at Terminal._cursorBlink (/Users/sam/.atom/packages/Termrk/node_modules/term.js/src/term.js:1324:8)
  at _blinker (/Users/sam/.atom/packages/Termrk/node_modules/term.js/src/term.js:1341:10)

```
### Commands

```
     -3:49.5.0 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -3:42.3.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -3:37.8.0 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused.autocomplete-active)
  5x -3:33.8.0 core:move-right (atom-text-editor.editor.mini.is-focused)
  3x -3:32.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:31.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:12.7.0 core:copy (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -3:10.8.0 core:paste (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
 10x -2:54.7.0 core:move-left (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -2:34.3.0 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  2x -2:08.3.0 core:copy (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:35.3.0 core:move-left (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  8x -1:34.6.0 core:move-right (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:31 core:paste (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:23.1.0 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  2x -0:31.7.0 termrk:toggle (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "themes": [
      "one-light-ui",
      "atom-light-syntax"
    ],
    "disabledPackages": [
      "language-asp",
      "linter-javac",
      "background-tips",
      "bookmarks",
      "language-c",
      "language-clojure",
      "language-go",
      "language-java",
      "language-mustache",
      "language-perl",
      "language-php",
      "language-python",
      "language-ruby-on-rails",
      "language-ruby",
      "language-sql",
      "language-toml",
      "welcome",
      "metrics",
      "open-on-github",
      "release-notes",
      "auto-run",
      "git-plus",
      "browser-plus"
    ]
  },
  "Termrk": {
    "startingDir": "home",
    "defaultHeight": 100
  }
}
```
### Installed Packages

``` coffee
# User
Termrk, v0.1.17
atom-beautify, v0.28.8
color-picker, v2.0.11
cucumber, v0.5.0
language-csharp, v0.6.0
language-gherkin, v1.0.2
language-mongodb, v0.2.0
language-spacebars, v0.2.2
meteor-api, v2.20.0
meteor-helper, v0.25.0
tree-view-git-status, v0.1.2
vim-mode, v0.57.0

# Dev
No dev packages
```

**Comment by romgrk** [comment]
Would it be possible to insert the following code in DevTools console, and give me a log of some MouseWheel events? 

``` javascript
document.addEventListener('mousewheel', function (ev) { console.log(ev); })
```

**Comment by amazingsam** [comment]
Would love to help you with that, however - when I replicate it, it crashes Atom.
Just add some commands in the pane, and accidently scroll up. Notifications will go off the charts, and Atom won't respond.
