### ISSUE TITLE
Uncaught TypeError (still) with v.0.1.22

### ISSUE THREAD

**Issue by mjrodgers** [romgrk/termrk#41]
Running the latest on OS X.

Problem is slightly different now! It used to trigger when I tried to scroll up (using trackpad).  Now I can scroll up, but it triggers the error when I try to scroll back down...

Uncaught TypeError: Cannot read property '0' of undefined
/Users/mrodgers/.atom/packages/Termrk/node_modules/term.js/src/term.js:1208
Hide Stack Trace
TypeError: Cannot read property '0' of undefined
  at Terminal.refresh (/Users/mrodgers/.atom/packages/Termrk/node_modules/term.js/src/term.js:1208:18)
  at Terminal.refresh (/Users/mrodgers/.atom/packages/Termrk/lib/termjs-fix.coffee:131:9)
  at Terminal.scrollDisp (/Users/mrodgers/.atom/packages/Termrk/node_modules/term.js/src/term.js:1401:8)
  at TermrkView.module.exports.TermrkView.terminalMousewheel (/Users/mrodgers/.atom/packages/Termrk/lib/termrk-view.coffee:165:19)
  at TermrkView.terminalMousewheel (/Users/mrodgers/.atom/packages/Termrk/lib/termrk-view.coffee:2:1)

**Comment by romgrk** [comment]
Well, that's something, at least it's getting better. 

Now, could you do me a favor and provide me a log of some MouseWheel events? I have no Mac to test on, and I'd like to see what it looks like.
All you need to do is insert the following code in the console, scroll anywhwere and it should log events.

``` javascript
document.addEventListener('mousewheel', function (ev) { console.log(ev); })
```

**Comment by mjrodgers** [comment]
Holy shit.  Logs tons of these.  Probably because of inertial scrolling.  May be related to this:
http://stackoverflow.com/questions/26326958/stopping-mousewheel-event-from-happening-twice-in-osx

Up down left right:

document.addEventListener('mousewheel', function (ev) { console.log(ev); })
undefined
VM575:2 WheelEvent {wheelDelta: -3, wheelDeltaY: -3, wheelDeltaX: 0, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -3, wheelDeltaY: -3, wheelDeltaX: 0, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -3, wheelDeltaY: -3, wheelDeltaX: 0, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -3, wheelDeltaY: -3, wheelDeltaX: 0, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -3, wheelDeltaY: -3, wheelDeltaX: 0, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -3, wheelDeltaY: -3, wheelDeltaX: 0, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -3, wheelDeltaY: -3, wheelDeltaX: 0, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -3, wheelDeltaY: -3, wheelDeltaX: 0, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -3, wheelDeltaY: -3, wheelDeltaX: 0, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -15, wheelDeltaY: -15, wheelDeltaX: 0, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -3, wheelDeltaY: -3, wheelDeltaX: 0, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -3, wheelDeltaY: -3, wheelDeltaX: 0, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -3, wheelDeltaY: -3, wheelDeltaX: 0, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -3, wheelDeltaY: -3, wheelDeltaX: 0, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -3, wheelDeltaY: -3, wheelDeltaX: 0, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -3, wheelDeltaY: -3, wheelDeltaX: 0, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -3, wheelDeltaY: -3, wheelDeltaX: 0, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -3, wheelDeltaY: -3, wheelDeltaX: 0, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -3, wheelDeltaY: -3, wheelDeltaX: 0, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -3, wheelDeltaY: -3, wheelDeltaX: 3, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 3, wheelDeltaY: 0, wheelDeltaX: 3, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 3, wheelDeltaY: 3, wheelDeltaX: 0, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 3, wheelDeltaY: 3, wheelDeltaX: 0, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 3, wheelDeltaY: 3, wheelDeltaX: 0, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 3, wheelDeltaY: 3, wheelDeltaX: 0, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 3, wheelDeltaY: 3, wheelDeltaX: 0, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 3, wheelDeltaY: 3, wheelDeltaX: 3, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 3, wheelDeltaY: 3, wheelDeltaX: 0, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 3, wheelDeltaY: 3, wheelDeltaX: 0, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 3, wheelDeltaY: 3, wheelDeltaX: 3, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 3, wheelDeltaY: 3, wheelDeltaX: 0, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 3, wheelDeltaY: 3, wheelDeltaX: 0, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 3, wheelDeltaY: 3, wheelDeltaX: 0, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 3, wheelDeltaY: 3, wheelDeltaX: 0, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 3, wheelDeltaY: 3, wheelDeltaX: 0, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 3, wheelDeltaY: 3, wheelDeltaX: 3, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 3, wheelDeltaY: 3, wheelDeltaX: 0, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 3, wheelDeltaY: 3, wheelDeltaX: 0, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 9, wheelDeltaY: 9, wheelDeltaX: 0, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 3, wheelDeltaY: 3, wheelDeltaX: 0, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 3, wheelDeltaY: 3, wheelDeltaX: 0, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 3, wheelDeltaY: 3, wheelDeltaX: 0, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -3, wheelDeltaY: 0, wheelDeltaX: -3, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -6, wheelDeltaY: 0, wheelDeltaX: -6, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -6, wheelDeltaY: 0, wheelDeltaX: -6, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -6, wheelDeltaY: 0, wheelDeltaX: -6, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -6, wheelDeltaY: 0, wheelDeltaX: -6, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -6, wheelDeltaY: 0, wheelDeltaX: -6, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -6, wheelDeltaY: 0, wheelDeltaX: -6, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -6, wheelDeltaY: 0, wheelDeltaX: -6, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -3, wheelDeltaY: 0, wheelDeltaX: -3, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -3, wheelDeltaY: 0, wheelDeltaX: -3, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -12, wheelDeltaY: 0, wheelDeltaX: -12, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -6, wheelDeltaY: 0, wheelDeltaX: -6, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -9, wheelDeltaY: 0, wheelDeltaX: -9, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -9, wheelDeltaY: 0, wheelDeltaX: -9, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -9, wheelDeltaY: 0, wheelDeltaX: -9, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -12, wheelDeltaY: 0, wheelDeltaX: -12, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -24, wheelDeltaY: 0, wheelDeltaX: -24, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -21, wheelDeltaY: 0, wheelDeltaX: -21, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -21, wheelDeltaY: 0, wheelDeltaX: -21, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -21, wheelDeltaY: 0, wheelDeltaX: -21, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -21, wheelDeltaY: 0, wheelDeltaX: -21, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -21, wheelDeltaY: 0, wheelDeltaX: -21, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -18, wheelDeltaY: 0, wheelDeltaX: -18, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -18, wheelDeltaY: 0, wheelDeltaX: -18, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -15, wheelDeltaY: 0, wheelDeltaX: -15, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -15, wheelDeltaY: 0, wheelDeltaX: -15, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -15, wheelDeltaY: 0, wheelDeltaX: -15, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -12, wheelDeltaY: 0, wheelDeltaX: -12, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -12, wheelDeltaY: 0, wheelDeltaX: -12, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -12, wheelDeltaY: 0, wheelDeltaX: -12, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -9, wheelDeltaY: 0, wheelDeltaX: -9, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -9, wheelDeltaY: 0, wheelDeltaX: -9, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -6, wheelDeltaY: 0, wheelDeltaX: -6, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -6, wheelDeltaY: 0, wheelDeltaX: -6, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -6, wheelDeltaY: 0, wheelDeltaX: -6, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -3, wheelDeltaY: 0, wheelDeltaX: -3, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -3, wheelDeltaY: 0, wheelDeltaX: -3, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -3, wheelDeltaY: 0, wheelDeltaX: -3, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -3, wheelDeltaY: 0, wheelDeltaX: -3, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -3, wheelDeltaY: 0, wheelDeltaX: -3, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -3, wheelDeltaY: 0, wheelDeltaX: -3, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -3, wheelDeltaY: 0, wheelDeltaX: -3, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -3, wheelDeltaY: 0, wheelDeltaX: -3, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -3, wheelDeltaY: 0, wheelDeltaX: -3, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -3, wheelDeltaY: 0, wheelDeltaX: -3, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -3, wheelDeltaY: 0, wheelDeltaX: -3, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 3, wheelDeltaY: 0, wheelDeltaX: 3, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 6, wheelDeltaY: 0, wheelDeltaX: 6, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 3, wheelDeltaY: 3, wheelDeltaX: 6, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 3, wheelDeltaY: 3, wheelDeltaX: 9, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 3, wheelDeltaY: 3, wheelDeltaX: 9, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 9, wheelDeltaY: 0, wheelDeltaX: 9, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 3, wheelDeltaY: 3, wheelDeltaX: 12, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 3, wheelDeltaY: 3, wheelDeltaX: 21, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 15, wheelDeltaY: 0, wheelDeltaX: 15, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 18, wheelDeltaY: 0, wheelDeltaX: 18, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 27, wheelDeltaY: 0, wheelDeltaX: 27, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -3, wheelDeltaY: -3, wheelDeltaX: 24, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: -3, wheelDeltaY: -3, wheelDeltaX: 27, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 54, wheelDeltaY: 0, wheelDeltaX: 54, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 102, wheelDeltaY: 0, wheelDeltaX: 102, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 48, wheelDeltaY: 0, wheelDeltaX: 48, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 48, wheelDeltaY: 0, wheelDeltaX: 48, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 45, wheelDeltaY: 0, wheelDeltaX: 45, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 42, wheelDeltaY: 0, wheelDeltaX: 42, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 42, wheelDeltaY: 0, wheelDeltaX: 42, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 39, wheelDeltaY: 0, wheelDeltaX: 39, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 36, wheelDeltaY: 0, wheelDeltaX: 36, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 33, wheelDeltaY: 0, wheelDeltaX: 33, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 30, wheelDeltaY: 0, wheelDeltaX: 30, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 27, wheelDeltaY: 0, wheelDeltaX: 27, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 24, wheelDeltaY: 0, wheelDeltaX: 24, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 24, wheelDeltaY: 0, wheelDeltaX: 24, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 21, wheelDeltaY: 0, wheelDeltaX: 21, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 18, wheelDeltaY: 0, wheelDeltaX: 18, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 18, wheelDeltaY: 0, wheelDeltaX: 18, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 15, wheelDeltaY: 0, wheelDeltaX: 15, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 15, wheelDeltaY: 0, wheelDeltaX: 15, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 15, wheelDeltaY: 0, wheelDeltaX: 15, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 12, wheelDeltaY: 0, wheelDeltaX: 12, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 12, wheelDeltaY: 0, wheelDeltaX: 12, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 12, wheelDeltaY: 0, wheelDeltaX: 12, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 9, wheelDeltaY: 0, wheelDeltaX: 9, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 9, wheelDeltaY: 0, wheelDeltaX: 9, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 6, wheelDeltaY: 0, wheelDeltaX: 6, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 6, wheelDeltaY: 0, wheelDeltaX: 6, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 6, wheelDeltaY: 0, wheelDeltaX: 6, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 6, wheelDeltaY: 0, wheelDeltaX: 6, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 3, wheelDeltaY: 0, wheelDeltaX: 3, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 3, wheelDeltaY: 0, wheelDeltaX: 3, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 3, wheelDeltaY: 0, wheelDeltaX: 3, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 3, wheelDeltaY: 0, wheelDeltaX: 3, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 3, wheelDeltaY: 0, wheelDeltaX: 3, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 3, wheelDeltaY: 0, wheelDeltaX: 3, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 3, wheelDeltaY: 0, wheelDeltaX: 3, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 3, wheelDeltaY: 0, wheelDeltaX: 3, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 3, wheelDeltaY: 0, wheelDeltaX: 3, deltaMode: 0, deltaZ: 0…}
VM575:2 WheelEvent {wheelDelta: 3, wheelDeltaY: 0, wheelDeltaX: 3, deltaMode: 0, deltaZ: 0…}
