### ISSUE TITLE
Uncaught TypeError: Cannot set property '0' of undefined

### ISSUE THREAD

**Issue by seyhaheng2** [romgrk/termrk#45]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.4
**System**: Mac OS X 10.10.4
**Thrown From**: [Termrk](https://github.com/romgrk/termrk) package, v0.1.22
### Stack Trace

Uncaught TypeError: Cannot set property '0' of undefined

```
At /Users/sino/.atom/packages/Termrk/node_modules/term.js/src/term.js:1501

TypeError: Cannot set property '0' of undefined
  at Terminal.write (/Users/sino/.atom/packages/Termrk/node_modules/term.js/src/term.js:1501:55)
  at /Users/sino/.atom/packages/Termrk/lib/termrk-view.coffee:138:23
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Users/sino/.atom/packages/Termrk/lib/termrk-model.coffee:97:22
  at Task.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:118:15)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:81:31)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at handleMessage (child_process.js:306:10)
  at Pipe.channel.onread (child_process.js:334:11)

```
### Commands

```
     -2:22.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -2:22.3.0 blur (atom-text-editor.editor.mini.is-focused)
  6x -2:18.7.0 core:backspace (atom-pane.pane.active)
  2x -2:16 blur (atom-pane.pane.active)
     -1:30.1.0 settings-view:open (atom-pane.pane.active)
  4x -1:29.8.0 blur (atom-pane.pane.active)
     -1:25.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 10x -1:19.1.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:34.5.0 termrk:toggle (atom-pane.pane.active)
  3x -0:34.1.0 blur (atom-pane.pane.active)
     -0:34 termrk:toggle (input.input-keylistener)
  2x -0:34 blur (input.input-keylistener)
     -0:33.8.0 termrk:toggle (input.input-keylistener)
     -0:33.8.0 blur (input.input-keylistener)
     -0:33.3.0 termrk:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  9x -0:04.6.0 blur (input.input-keylistener)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
Termrk, v0.1.22
clipboard-plus, v0.5.1
emmet, v2.3.12
ex-mode, v0.7.0
hide-tree, v0.0.11
linter, v1.3.1
linter-js-standard, v2.4.0
meteor-api, v2.20.0
pigments, v0.9.3
vim-mode, v0.57.0
vim-mode-clipboard-plus, v0.1.0
vim-surround, v0.8.0

# Dev
No dev packages
```

**Comment by romgrk** [comment]
Not enough information. Try updating. Provide steps to reproduce if it happens again.
