### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getURI' of undefined

### ISSUE THREAD

**Issue by Kuberchaun** [romgrk/termrk#55]
[Enter steps to reproduce below:]
1. Click directory in project side bar
2. Press control + alt + space

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.4
**Thrown From**: [Termrk](https://github.com/romgrk/termrk) package, v0.1.26
### Stack Trace

Uncaught TypeError: Cannot read property 'getURI' of undefined

```
At /Users/henkbl/.atom/packages/Termrk/lib/utils.coffee:61

TypeError: Cannot read property 'getURI' of undefined
  at Object.Utils.getCurrentDir (/Users/henkbl/.atom/packages/Termrk/lib/utils.coffee:61:58)
  at atom-workspace.registerCommands.termrk:create-terminal-current-dir (/Users/henkbl/.atom/packages/Termrk/lib/termrk.coffee:73:63)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```
### Commands

```
     -4:14.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -3:46.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:41 core:backspace (atom-text-editor.editor.mini.is-focused)
  9x -3:09.7.0 termrk:toggle (atom-text-editor.editor.is-focused)
     -1:04.5.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:14.6.0 command-palette:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:13.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:13.2.0 settings-view:open (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:01.0 termrk:create-terminal-current-dir (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "linter-puppet-lint",
      "dash"
    ]
  },
  "Termrk": {}
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.7.2
Termrk, v0.1.26
autocomplete-ruby, v0.1.0
file-icons, v1.6.6
jsonpp, v0.1.1
language-docker, v1.1.3
language-gradle, v0.0.3
language-powershell, v2.0.2
language-puppet, v0.14.0
language-salt, v0.4.0
linter, v1.4.3
remote-edit, v1.8.15
ruby-block, v0.3.5

# Dev
No dev packages
```

**Comment by romgrk** [comment]
Fixed by 201debdd5241d0cd4bd397b2b45cdcdc09a26595.
