### ISSUE TITLE
Missing underscore-plus package

### ISSUE THREAD

**Issue by ghost** [romgrk/termrk#6]
Hello

My apologies if this is an issue on my side, but since I updated to Atom 0.200 and the latest version of termrk, I can no longer actually open the terminal. I get the following error:

```
Error: Cannot find module 'underscore-plus'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/home/me/.atom/packages/Termrk/lib/utils.coffee:4:7)
    at Object.<anonymous> (/home/me/.atom/packages/Termrk/lib/utils.coffee:171:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/usr/share/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
```

Is there perhaps a missing dependency I must install?

Thanks in advance and thanks for a quick fix of the 'exit' issue :).

**Comment by romgrk** [comment]
No, the problem was on my side, forgot to update dependencies in package.json. Patch published just now, it should solve it.

**Comment by ghost** [comment]
The problem is solved, thanks :).
