### ISSUE TITLE
termrk throws TypeError on input.

### ISSUE THREAD

**Issue by simar7** [romgrk/termrk#62]
Hello,

While working with termrk, I had a mosh session open and a ipython instance running on the remote server when I tried to enter the '%' character. For some reason, termrk threw an TypeError Exception on my input of the % character. Here's the log:

[steps to reproduce below:]
1. Open termrk, connect to a remote server via a mosh session. Run ipython.
2. Enter the % (percent symbol, shift+5)

**Atom Version**: 1.0.11
**System**: Mac OS X 10.10.5
**Thrown From**: [termrk](https://github.com/romgrk/termrk) package, vundefined
### Stack Trace

Uncaught TypeError: Cannot read property 'originalEvent' of undefined

```
At /Users/simar/.atom/packages/termrk/lib/termrk-view.coffee:185

TypeError: Cannot read property 'originalEvent' of undefined
  at TermrkView.module.exports.TermrkView.triggerKeypress (/Users/simar/.atom/packages/Termrk/lib/termrk-view.coffee:185:45)
  at TermrkView.triggerKeypress (/Users/simar/.atom/packages/Termrk/lib/termrk-view.coffee:2:1)
  at space-pen-div.registerCommands.termrk:trigger-keypress (/Users/simar/.atom/packages/Termrk/lib/termrk.coffee:78:29)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at KeymapManager.module.exports.KeymapManager.terminatePendingState (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:498:14)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:374:23)
  at TermrkView.module.exports.TermrkView.inputKeydown (/Users/simar/.atom/packages/Termrk/lib/termrk-view.coffee:147:22)
  at TermrkView.inputKeydown (/Users/simar/.atom/packages/Termrk/lib/termrk-view.coffee:2:1)
  at HTMLInputElement.<anonymous> (/Users/simar/.atom/packages/Termrk/lib/termrk-view.coffee:113:54)

```
### Commands

```
     -1:43.9.0 core:move-right (atom-text-editor.editor.is-focused)
  6x -1:43 core:move-down (atom-text-editor.editor.is-focused)
  4x -1:41.8.0 core:move-up (atom-text-editor.editor.is-focused)
 14x -1:40.8.0 core:move-right (atom-text-editor.editor.is-focused)
  5x -1:39.7.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -1:37 core:move-right (atom-text-editor.editor.is-focused)
 11x -1:34.4.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:20.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:20 core:move-left (atom-text-editor.editor.is-focused)
     -1:19.8.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -1:16 core:move-right (atom-text-editor.editor.is-focused)
  2x -1:08.9.0 core:move-left (atom-text-editor.editor.is-focused)
  8x -1:03.0 core:move-right (atom-text-editor.editor.is-focused)
  5x -1:01.9.0 core:move-left (atom-text-editor.editor.is-focused)
  7x -0:59 core:move-right (atom-text-editor.editor.is-focused)
     -0:01.4.0 termrk:trigger-keypress (input.input-keylistener)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "deprecation-cop",
      "fuzzy-finder",
      "incompatible-packages",
      "metrics",
      "styleguide",
      "timecop",
      "tree-view"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Termrk, v0.1.26
autocomplete-plus-clang, v0.0.0
autocomplete-python, v0.5.3
buck, v0.0.0
debugger-hhvm, v0.0.0
debugger-lldb, v0.0.0
graphql, v0.0.0
haskell-grammar, v0.3.0
hyperclick, v0.0.0
language-ocaml, v1.1.1
linter-python-pep8, v0.2.0
nuclide-arcanist, v0.0.0
nuclide-blame, v0.0.0
nuclide-blame-provider-hg, v0.0.0
nuclide-blame-ui, v0.0.0
nuclide-code-format, v0.0.0
nuclide-debugger, v0.0.0
nuclide-debugger-node, v0.0.0
nuclide-diagnostics-store, v0.0.0
nuclide-diagnostics-ui, v0.0.0
nuclide-diff-view, v0.0.0
nuclide-file-creation, v0.0.0
nuclide-file-creation-ios, v0.0.0
nuclide-file-tree, v0.0.0
nuclide-file-tree-deux, v0.0.0
nuclide-file-watcher, v0.0.0
nuclide-find-references, v0.0.0
nuclide-flow, v0.0.0
nuclide-format-js, v0.0.0
nuclide-fuzzy-filename-provider, v0.0.0
nuclide-hack, v0.0.0
nuclide-hg-repository, v0.0.0
nuclide-language-hack, v0.0.0
nuclide-log-viewer, v0.0.0
nuclide-logging-helper, v0.0.0
nuclide-objc, v0.0.0
nuclide-ocaml, v0.0.0
nuclide-open-filenames-provider, v0.0.0
nuclide-quick-open, v0.0.0
nuclide-remote-projects, v0.0.0
nuclide-tabs-per-branch, v0.0.0
nuclide-test-runner, v0.0.0
nuclide-toolbar, v0.0.0
nuclide-type-hint, v0.0.0

# Dev
No dev packages
```

**Comment by romgrk** [comment]
Yep, entering `% f` is mapped on inserting current file name, and `%` on inserting `'%'` after the keymap delay.
You can unmap it with 

```
'.termrk':
    '%': 'abort!'
```

I don't know what's causing the issue on this particular situation.

**Comment by simar7** [comment]
Trying to reproduce this again.

**Comment by simar7** [comment]
Oops, accidentally closed it. Re-opening.
