### ISSUE TITLE
Uncaught TypeError: _ref1.destroy is not a function

### ISSUE THREAD

**Issue by crobles-afk** [romgrk/termrk#77]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.6.0
**System**: linux 4.4.5-1-ARCH
**Thrown From**: [Termrk](https://github.com/romgrk/termrk) package, v0.2.3
### Stack Trace

Uncaught TypeError: _ref1.destroy is not a function

```
At /home/chechare/.atom/packages/Termrk/lib/termrk-model.coffee:108

TypeError: _ref1.destroy is not a function
    at TermrkModel.module.exports.TermrkModel.destroy (/home/chechare/.atom/packages/Termrk/lib/termrk-model.coffee:108:15)
    at TermrkView.module.exports.TermrkView.destroy (/home/chechare/.atom/packages/Termrk/lib/termrk-view.coffee:326:17)
    at /home/chechare/.atom/packages/Termrk/lib/termrk.coffee:230:35
    at space-pen-div.<anonymous> (/home/chechare/.atom/packages/Termrk/lib/termrk-view.coffee:247:13)
    at space-pen-div.opt.complete (/home/chechare/.atom/packages/Termrk/node_modules/space-pen/node_modules/jquery/dist/jquery.js:6693:12)
    at fire (/home/chechare/.atom/packages/Termrk/node_modules/space-pen/node_modules/jquery/dist/jquery.js:3099:30)
    at Object.self.fireWith [as resolveWith] (/home/chechare/.atom/packages/Termrk/node_modules/space-pen/node_modules/jquery/dist/jquery.js:3211:7)
    at Animation.tick (/home/chechare/.atom/packages/Termrk/node_modules/space-pen/node_modules/jquery/dist/jquery.js:6569:14)
    at jQuery.fx.tick (/home/chechare/.atom/packages/Termrk/node_modules/space-pen/node_modules/jquery/dist/jquery.js:6858:9)
```
### Commands

```
     -0:03.6.0 command-palette:toggle (input.input-keylistener)
     -0:02.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.9.0 termrk:close-terminal (input.input-keylistener)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true
  },
  "Termrk": {
    "defaultHeight": 146
  }
}
```
### Installed Packages

``` coffee
# User
Termrk, v0.2.3
color-picker, v2.1.1
file-icons, v1.6.18
fonts, v1.2.0
minimap, v4.21.0
open-on-bitbucket, v0.4.0

# Dev
No dev packages
```

**Comment by romgrk** [comment]
Patch 0.2.4 https://github.com/romgrk/termrk/commit/50c804ab668052394a1b66bd647fb5ba37c4cad0

This happens for not updating correctly the references to `termrk.views` (introduced by 0.2.3).

@Chechare reopen if this still pops. It shouldn't.
