### ISSUE TITLE
Error in atom 1.11

### ISSUE THREAD

**Issue by ghost** [romgrk/termrk#87]
Hello

It seems that issue #54 started occurring for me after upgrading to Atom 1.11.2. Usually Atom requests me to rebuild the Termrk module after an upgrade, which did not happen this time. To be entirely sure, I tried completely removing the package and installing it manually again. Unfortunately that didn't seem to help.

The issue occurs when I try to open the terminal for the first time. I'm also getting a second error simultaneously, which may or may not be related. I've attached the backtrace of both errors:

```
TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (/usr/lib/atom/node_modules/event-kit/lib/composite-disposable.js:70:13)
    at CompositeDisposable.module.exports.CompositeDisposable.add (/usr/lib/atom/node_modules/event-kit/lib/composite-disposable.js:43:11)
    at Object.activate (/home/me/.atom/packages/Termrk/lib/termrk.coffee:98:24)
    at Package.module.exports.Package.activateNow (/usr/lib/atom/src/package.js:183:20)
    at /usr/lib/atom/src/package.js:801:25
    at Function.module.exports.Emitter.simpleDispatch (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:129:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/lib/atom/src/command-registry.js:241:20)
    at /usr/lib/atom/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/lib/atom/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/lib/atom/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/lib/atom/src/window-event-handler.js:114:36)
    at HTMLDocument.<anonymous> (/usr/lib/atom/src/window-event-handler.js:3:61)
```

```
TypeError: Cannot read property 'isVisible' of null
    at Object.toggle (/home/me/.atom/packages/Termrk/lib/termrk.coffee:271:18)
    at atom-workspace.registerCommands.termrk:toggle (/home/me/.atom/packages/Termrk/lib/termrk.coffee:53:45)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/lib/atom/src/command-registry.js:260:29)
    at /usr/lib/atom/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/lib/atom/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/lib/atom/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/lib/atom/src/window-event-handler.js:114:36)
    at HTMLDocument.<anonymous> (/usr/lib/atom/src/window-event-handler.js:3:61)
```

Thanks in advance

**Comment by ghost** [comment]
Apologies, it seems this is due to my usage of an unofficial Atom distribution (from my Linux distribution). Installing the official Atom 1.11 seems to fix the issue.
